// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using New_Revision.Models;

#nullable disable

namespace New_Revision.Migrations
{
    [DbContext(typeof(HeroesDbContext))]
    [Migration("20240623071426_TitleColumnAdded")]
    partial class TitleColumnAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("New_Revision.Models.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Power")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("Heroes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ironman",
                            Power = "Rich",
                            Rank = 1,
                            Title = "Ironman"
                        });
                });

            modelBuilder.Entity("New_Revision.Models.Movie", b =>
                {
                    b.Property<string>("Title")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Title");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Title = "Ironman",
                            MovieId = 1
                        });
                });

            modelBuilder.Entity("New_Revision.Models.Hero", b =>
                {
                    b.HasOne("New_Revision.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("Title");

                    b.Navigation("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
