// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _15._EntityFramerworkCore.Models;

#nullable disable

namespace _15._EntityFramerworkCore.Migrations
{
    [DbContext(typeof(PersonsDbContext))]
    partial class PersonsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_15._EntityFramerworkCore.Models.JobDetails", b =>
                {
                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("JobTitle");

                    b.ToTable("JobDetails", (string)null);

                    b.HasData(
                        new
                        {
                            JobTitle = "Front-End Developer",
                            Salary = 999999.0
                        },
                        new
                        {
                            JobTitle = "Back-End Developer",
                            Salary = 899999.0
                        },
                        new
                        {
                            JobTitle = "Database Developer",
                            Salary = 799999.0
                        },
                        new
                        {
                            JobTitle = "Graphic Designer",
                            Salary = 599999.0
                        },
                        new
                        {
                            JobTitle = "Full Stack Developer",
                            Salary = 99999999999.0
                        });
                });

            modelBuilder.Entity("_15._EntityFramerworkCore.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Gender")
                        .HasColumnType("Male")
                        .HasColumnName("PersonGender");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("JobTitle");

                    b.ToTable("Persons", (string)null);

                    b.HasCheckConstraint("CHK_Email", "len(email) > 5");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Age = 8,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "shanchan@hungama.com",
                            Name = "Shinchan"
                        },
                        new
                        {
                            Id = 6,
                            Age = 18,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "light@deathnote.com",
                            Name = "Light"
                        });
                });

            modelBuilder.Entity("_15._EntityFramerworkCore.Models.Person", b =>
                {
                    b.HasOne("_15._EntityFramerworkCore.Models.JobDetails", "JobDetails")
                        .WithMany("Persons")
                        .HasForeignKey("JobTitle");

                    b.Navigation("JobDetails");
                });

            modelBuilder.Entity("_15._EntityFramerworkCore.Models.JobDetails", b =>
                {
                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
